name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout madprobe
      uses: actions/checkout@v2        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag madjlzz/madprobe:${GITHUB_SHA::8}
    - name: Login to DockerHub
      run: printf $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish the Docker image
      run: docker push registry-host:5000/myadmin/rhel-httpd
