name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout madprobe
      uses: actions/checkout@v2        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag madjlzz/madprobe:${GITHUB_SHA::8}
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Publish the Docker image
      run: docker push registry-host:5000/myadmin/rhel-httpd
