name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout madprobe
      uses: actions/checkout@v2        
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        # Docker repository to tag the image with
        repository: madjlzz/madprobe
        # Automatically tags the built image with the git short SHA as per the readme
        tag_with_sha: true
